### ISSUE TITLE
I validated on the imagenetnet1k dataset and constructed subcategories using wordnet, but the results significantly worsened

### ISSUE THREAD

**Issue by pandaupc** [acmi-lab/CHILS#1]

**Comment by ZacharyNovack** [comment]
Hello,

Note that the main use-case for CHiLS is for tasks specifically with implicit class hierarchies; ImageNet1k is generally something that is _not_ in that use-case, as most classes in ImageNet1k are already at a semantically fine-grained level. See Section 4 of the paper for a short walkthrough on ImageNet1k performance at different depths of the hierarchy, as well as 5.4 paragraph 3, which shows than in the presence of uninformative subcategories performance degrades.

Also note that in our work, we specifically use the **BREEDS** construction of the ImageNet hierarchy, not wordnet directly. Though the class structure of ImageNet comes from wordnet, we found that in our own experiments using wordnet directly is rather difficult, namely because wordnet's graph is not directly usable as a tree hierarchy (more specifically, words with similar semantic granularities may be at different depths from the same root note). The **BREEDS** construction of the ImageNet1k hierarchy fixes this however, by expliciting editing wordnet to fit a more balanced tree-like structure, which is what we used for all experiments involving ImageNet subsets.
